#Updated at 2025-06-03 14:40:32
#Tue Jun 03 14:40:32 CST 2025
outputFolderEnabledFlag=true
callbackHookEnabledFlag=true
localIp=192.168.1.32
outputFolderPath=C\:\\Projects\\PT-OCR\\Screenshots
updateStatusHookUrl=http\://localhost\:8888/ocr/update-status
callbackHookUrl=http\://localhost\:8888/ocr/callback
intervalSeconds=5
databaseEnabledFlag=true
stopWarningHookUrl=http\://localhost\:8888/ocr/stop-warning
