#Updated at 2025-05-15 15:58:48
#Thu May 15 15:58:48 CST 2025
outputFolderEnabledFlag=true
callbackHookEnabledFlag=true
outputFolderPath=C\:\\Projects\\PT-OCR\\Screenshots
updateStatusHookUrl=http\://localhost\:8888/ocr/update-status
callbackHookUrl=http\://localhost\:8888/ocr/callback
intervalSeconds=5
databaseEnabledFlag=true
