#Updated at 2025-06-27 15:18:04
#Fri Jun 27 15:18:04 CST 2025
outputFolderEnabledFlag=true
callbackHookEnabledFlag=true
asyncFlag=false
localIp=192.168.137.1
outputFolderPath=C\:\\Projects\\PT-OCR\\Screenshots
updateStatusHookUrl=http\://localhost\:8888/ocr/update-status
fieldNameOptions=\u5B57\u6BB5\#1,\u5B57\u6BB5\#2,\u5B57\u6BB5\#3,\u5B57\u6BB5\#4,\u5B57\u6BB5\#5,\u5B57\u6BB5\#6,\u5B57\u6BB5\#7,\u5B57\u6BB5\#8,\u5B57\u6BB5\#9,\u5B57\u6BB5\#10
callbackHookUrl=http\://localhost\:8888/ocr/callback
intervalSeconds=5
databaseEnabledFlag=true
stopWarningHookUrl=http\://localhost\:8888/ocr/stop-warning
